version: '3'

services:
  front:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      #target: development
    volumes:
      - front:/usr/src/app
    #Run in dev Mode: npm run start:dev  // start:dev ?
    command: npm run dev
    ports:
      - 5173:5173

volumes:
  front: